## Numpy

numpy is a fundamental library for scientific computing in Python. it provides support for arrays and matrices, along with a collection of mathematical functions to operate on these data structures.

In [1]:
!pip install numpy

In [3]:
import numpy as np

##Create arrays using numpy
## create a 1D array
arr1=np.array([1,2,3,4,5])
print(arr1)
print(type(arr1))
print(arr1.shape) ##--(5,)--> Single Dimension

[1 2 3 4 5]
<class 'numpy.ndarray'>
(5,)


In [4]:
##1D array
arr2=np.array([1,2,3,4,5])
arr2.reshape(1,5) ##1 row and 25 collumns

array([[1, 2, 3, 4, 5]])

In [7]:
arr2=np.array([[1,2,3,4,5]])
arr2.shape

(1, 5)

In [ ]:
##2D array
arr2=np.array([[1,2,3,4,5],[6,7,8,9,0]])
print(arr2)

arr2.shape ##---> 2 rows and 5 columns

[[1 2 3 4 5]
 [6 7 8 9 0]]


(2, 5)

In [6]:
import numpy as np

In [11]:
np.arange(0,10,2).reshape(5,1)

array([[0],
       [2],
       [4],
       [6],
       [8]])

In [13]:
np.ones((3,4))## --> its going to create 3 rows and 4 columns with Ones

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [14]:
##identity matrix/array
np.eye(3) ##-> 3x3 identity matrix 

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [20]:
## attributes of Numoy Array

arr=np.array([[1,2,3],[4,5,6]])

print("Array: \n", arr)
print("Shape:", arr.shape) ##Output (2,3)
print("Number of dimensions :", arr.ndim) ##Output : 2
print("Size (number of elements):", arr.size) ## Output :6
print("Data Type :", arr.dtype) ##output: int64(may vary based on platform)
print("Item size (in bytes) :", arr.itemsize) ##Output : 8

Array: 
 [[1 2 3]
 [4 5 6]]
Shape: (2, 3)
Number of dimensions : 2
Size (number of elements): 6
Data Type : int64
Item size (in bytes) : 8


In [17]:
##Numpy Vectorized Operation 
arr1=np.array([1,2,3,4,5])
arr2=np.array([10,20,30,40,50])

##elements wise addition
print("Addition: ", arr1+arr2)

##element wise substraction
print("Substraction", arr1-arr2)

##element wise multiplication
print("Multiplication ", arr1*arr2)

##element wise division
print("Division ", arr1/arr2)

Addition:  [11 22 33 44 55]
Substraction [ -9 -18 -27 -36 -45]
Multiplication  [ 10  40  90 160 250]
Division  [0.1 0.1 0.1 0.1 0.1]


In [ ]:
## Universal Function(ufuncs)

arr=np.array([2,3,4,5,6])
print(np.sqrt(arr)) ## square root

print(np.exp(arr)) ##exponential

print(np.sin(arr)) ##sine

print(np.log(arr)) ##natural log

[1.41421356 1.73205081 2.         2.23606798 2.44948974]
[  7.3890561   20.08553692  54.59815003 148.4131591  403.42879349]
[ 0.90929743  0.14112001 -0.7568025  -0.95892427 -0.2794155 ]
[0.69314718 1.09861229 1.38629436 1.60943791 1.79175947]


In [24]:
## array slicing and iNdexing

arr=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print("Array: \n", arr)

Array: 
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [55]:
print(arr[1:,1:3])

[[ 6  7]
 [10 11]]


In [47]:
print(arr[0][0]) ## 1st row 1st element
print(arr[0:2,2:])

1
[[3 4]
 [7 8]]


In [34]:
arr[1:,2:] ##2nd & 3rd row  and 3rd & 4th  columns elements

array([[ 7,  8],
       [11, 12]])

In [56]:
##Modify array elements
arr[0,0] = 100
print(arr)

[[100   2   3   4]
 [  5   6   7   8]
 [  9  10  11  12]]


In [57]:
arr[1:]=100
print(arr)

[[100   2   3   4]
 [100 100 100 100]
 [100 100 100 100]]


In [58]:
## Statitical Concept -- Normalisation
##to have a mean of 0 and standard deviation of 1

data = np.array([1,2,3,4,5])

##Calculate the mean and Standard deviation
mean=np.mean(data)
std_dev=np.std(data)

##Normalize the data
normalized_data=(data-mean)/std_dev
print("Normalized data : ", normalized_data)

Normalized data :  [-1.41421356 -0.70710678  0.          0.70710678  1.41421356]


In [60]:
data=np.array([1,2,3,4,5,6,7,8,9,10])

#mean
mean = np.mean(data)
print("Mean : ", mean)

#median
median= np.median(data)
print("Median : ",median)

#Standard Deviation
std=np.std(data)
print("Standard Deviation : ", std)

##variance
var=np.var(data)
print("Variance : ",var)

Mean :  5.5
Median :  5.5
Standard Deviation :  2.8722813232690143
Variance :  8.25


In [68]:
##logical operations

data=np.array([1,2,3,4,5,6,7,8,9,10])

data[(data>=5) & (data<=8)]

array([5, 6, 7, 8])